name: Capture Webpage Screenshot

# Trigger the workflow manually or on a schedule
on:
  schedule:
    - cron: '* * * * *'  # This will run daily at 12:00 UTC
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # or any version of Node.js

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Run Puppeteer script to capture the screenshot
      run: node capture.js

    - name: Commit the new screenshot
      run: |
        git config --global user.email "harshil8595@gmail.com"
        git config --global user.name "Harshil Patel"
        git add screenshots/*
        git commit -m "Automated screenshot capture"

    # Push changes back to the repository
    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main  # Specify the branch to push changes to
